#!/usr/bin/env bash
#MISE description="Run unit tests"
#USAGE flag "-v --verbose" help="Verbose output"

set -euo pipefail

verbose="${usage_verbose:-false}"

args=(tests)
[ "$verbose" = "true" ] && args+=(-v)
uv run --group dev pytest "${args[@]}"
